### ISSUE TITLE
[Feature Request] Currency tab currently has no button to copy GUID to clipboard.

### ISSUE THREAD

**Issue by Jdance-Media** [iBowie/BowieD.Unturned.NPCMaker#22]
So, currency assets can be created in the editor, but the issue is that I cannot grab the GUID of the asset unless I export it and find it in the files. This is time consuming and really annoying, so I think you should be able to press a button to copy the GUID of your currency assets so you can paste it in other fields in the editor.

**Comment by iBowie** [comment]
Looks obvious enough, will add!

**Comment by iBowie** [comment]
Added in 1.16.2
