### ISSUE TITLE
I made a Scan And It found a virus or something on the file?

### ISSUE THREAD

**Issue by GhostToprak** [iBowie/BowieD.Unturned.NPCMaker#34]
https://www.virustotal.com/gui/file/f4aff74f9f0990ab348c8ac4062f7f996898392b800df04e50b70307588f49f4

**Comment by iBowie** [comment]
It's literally open source...

**Comment by iBowie** [comment]
So I took a peek at why exactly it detects, and I can confidently say that to remove this false detection I would need to remove uploading to Steam workshop from the app.

**Comment by GhostToprak** [comment]
Thanks for your App It helps a lot.
