### ISSUE TITLE
[BUG] Something isn't right

### ISSUE THREAD

**Issue by zorro6969** [iBowie/BowieD.Unturned.NPCMaker#37]
![image](https://github.com/iBowie/BowieD.Unturned.NPCMaker/assets/138833912/15f7e46f-b5a2-40fa-ba87-8d552a91a6bf)
When i make a quest npc it says that i need a dialogue to the reply with the quest but when i test in game it doesn't even take me to the quest, it just takes me to the next dialogue taht it told me to add.

**Comment by iBowie** [comment]
I suggest you read the guide on making quests: https://steamcommunity.com/sharedfiles/filedetails/?id=1664300090

It's not a bug with the app.
