### ISSUE TITLE
This is more like a request/question.

### ISSUE THREAD

**Issue by Nanaimo2013** [iBowie/BowieD.Unturned.NPCMaker#40]
##
**Hi there,**

I've been using your **NPCMaker** for a while now, and its functionality and UI are nice and good-looking. Recently, I've wanted to apply a similar concept or adapt certain elements from your **NPCMaker** for another game, **Hearts of Iron IV (HOI4)**.

Before proceeding, I would like your permission to ensure that you're comfortable with the idea. I'm particularly interested in borrowing ideas related to:
##
**1. UI Design
2. Tab Structure
3. File Management
4. Code** 
##
I've noticed that there are barely any up-to-date and effective and barely mod editors for **HOI4**, and your **NPCMaker** serves as a good example. If you're open to it, I would appreciate your insights or any guidance you can provide in this regard.

For reference, **HOI4** is available on [Steam](https://store.steampowered.com/app/394360/Hearts_of_Iron_IV/), and you can find additional information on the [HOI4 Wiki](https://hoi4.paradoxwikis.com/Hearts_of_Iron_4_Wiki). 
##
Thank you for considering my request, and I look forward to your thoughts on this matter.
**Best regards,**
[Nanaimo2013](https://github.com/Nanaimo2013)
[NansHOI4ModdingTool](https://github.com/Nanaimo2013/Nanshoi4moddingtool)

**Comment by iBowie** [comment]
Yeah, sure, I have no problem with other people being inspired by the things I made!
Best wishes to your project as well!
