### ISSUE TITLE
[REQUEST] French Translation

### ISSUE THREAD

**Issue by julien040** [iBowie/BowieD.Unturned.NPCMaker#5]
**Présentation**
Hey, we are a French Unturned Server, and we love your NPC Maker

**Translation :**
A lot of french people use your tool to make some NPC.
We would like to help you on this subject
We would be able to provide you with a French translation of your application. Explain to us how to do it, and we will do it

**Contact :**
If you wish to contact us again, please answer this issues.
Or send me a Discord message : Julien#6569
Or send a mail to [admin@lakoya-rp.fr](mailto:admin@lakoya-rp.fr)

Good luck for the future

**Comment by julien040** [comment]
**Update :**
We find how to do that. We have already begun the translation 😃

**Comment by julien040** [comment]
We have already completed 50% of the translation.
The release will be soon 😉

**Comment by julien040** [comment]
Why do you close this issues. You have newer answered me about this translation. So I stopped the project, but I can restart it.

**Comment by iBowie** [comment]
ok, i just thought you stopped working on it and it was quite a lot of time, sorry about it

**Comment by iBowie** [comment]
French localization was added to the app recently
